# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cce964017c1dc2bc237f5749cf8c3e1c833221a0b46791c58a4d2581eed36ffd028447bd98678fb97c5231f6f8cf0b46eb0d8d17ee3d430689d774ec08a7b4a

test:
  secret_key_base: 9a1c7ece4eb664636530c4449527c44ff7bbb5fcc0437c0d1b8a5bdc07a00028868fa3f1734dee0bacf7e3a690475712858b043964b9f8384abfd5c364481a96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
